pipeline {
    agent any
    tools {nodejs "node"}
    stages {
        stage ('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }
        stage ('Deployment Stage') {
            steps {
                bat 'npm build'
            }
    }
    }
}